# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 09:21
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20161103_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=versatileimagefield.fields.VersatileImageField(upload_to='photo/', verbose_name='Image'),
        ),
    ]
